import { useEffect, useState } from "react";
import { Activity, Database, Download, LockKeyhole, Monitor, Plus, RefreshCw, ShieldCheck, Trash2, TriangleAlert } from "lucide-react";
import { authRequest, clearLocalPersonalData } from "../lib/api.js";

const dateTime = value => {const date=new Date(value);if(Number.isNaN(date.getTime()))return "nem ismert";return new Intl.DateTimeFormat("hu-HU",{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(date)};
const readJson = url => fetch(url,{cache:"no-store",credentials:"same-origin"}).then(response=>response.ok?response.json():null).catch(()=>null);

export function DataManagementOverview({garminStatus}){const [dashboard,setDashboard]=useState(null),[syncStatus,setSyncStatus]=useState(null),[loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;Promise.all([readJson("/api/dashboard"),readJson("/api/sync")]).then(([dashboardData,syncData])=>{if(!active)return;setDashboard(dashboardData);setSyncStatus(syncData);setLoading(false)});return()=>{active=false}},[]);
  const sessions=dashboard?.sessions||[],dates=sessions.map(item=>item.date).filter(Boolean).sort(),hasHistory=sessions.length>0,syncDate=syncStatus?.completed_at||syncStatus?.updated_at||dashboard?.generatedAt,
    connectionState=garminStatus===null?"Kapcsolat ellenőrzése…":garminStatus?.status==="connected"?"Csatlakoztatva":"Nincs aktív kapcsolat",
    connectionDetail=garminStatus?.status==="connected"?"Titkosított munkamenettoken; Garmin-jelszót nem tárolunk.":garminStatus?.status==="reauth_required"?"A Garmin-munkamenet lejárt; új szinkron csak ismételt csatlakoztatás után indítható.":"A szinkronhoz csatlakoztasd a Garmin-fiókodat fent.";
  return <section className="card data-management-card" aria-labelledby="data-management-title"><span className="eyebrow">ADATKEZELÉSI ÁTTEKINTŐ</span><h2 id="data-management-title">Milyen adatok vannak a fiókodban?</h2><p>Az összefoglaló elkülöníti a Garmin-kapcsolatot, a szinkronizált sportelőzményeket és a saját beállításaidat. A Garmin leválasztása nem jelenti automatikusan a korábban szinkronizált adatok törlését.</p>
    <div className="data-management-grid"><article><Activity size={21} aria-hidden="true"/><div><strong>Garmin-kapcsolat</strong><span>{connectionState}</span><small>{connectionDetail}</small></div></article>
      <article><Database size={21} aria-hidden="true"/><div><strong>Szinkronizált sportelőzmények</strong><span>{loading?"Állapot betöltése…":hasHistory?`${sessions.length.toLocaleString("hu-HU")} legutóbbi edzés`:"Még nincs szinkronizált edzés"}</span><small>{hasHistory?`${dates[0]} – ${dates[dates.length-1]}`:"A hiányzó adatot nem helyettesítjük mintaértékkel."}</small></div></article>
      <article><RefreshCw size={21} aria-hidden="true"/><div><strong>Legutóbbi feldolgozás</strong><span>{loading?"Állapot betöltése…":syncDate?dateTime(syncDate):"nincs adat"}</span><small>{syncStatus?.status==="running"?`Szinkronizálás folyamatban · ${Math.round(syncStatus.progress||0)}%`:syncStatus?.status==="failed"?"A legutóbbi szinkron megszakadt; a Ma oldalon folytatható.":"A dashboard ennek az adatállapotnak az összesítését mutatja."}</small></div></article>
      <article><ShieldCheck size={21} aria-hidden="true"/><div><strong>Saját megadott adatok</strong><span>Profil, tervek, check-inek, edzésérzet és az Edzőtárs memóriája</span><small>Ezek a Garmin leválasztása után is megmaradnak, és a saját adatexport részei.</small></div></article></div>
    <div className="data-management-note"><LockKeyhole size={18} aria-hidden="true"/><span>A teljes fiók- és adattörlés külön, jelszóval védett művelet a lap alján. A letölthető exporttal előtte ellenőrizheted a rólad tárolt adatokat.</span></div></section>}

export function ActiveSessionsCard(){const [sessions,setSessions]=useState([]),[busyId,setBusyId]=useState(""),[error,setError]=useState("");
  useEffect(()=>{fetch("/api/sessions").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setSessions((body.sessions||[]).filter(item=>item?.id&&item?.device))}).catch(reason=>setError(reason.message||"A munkamenetek nem tölthetők be."))},[]);
  const revoke=async session=>{if(!globalThis.confirm?.(`Biztosan kijelentkezteted ezt az eszközt?\n\n${session.device}`))return;setBusyId(session.id);setError("");try{const response=await fetch("/api/sessions",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:session.id})}),body=await response.json();if(!response.ok)throw new Error(body.error);setSessions(items=>items.filter(item=>item.id!==session.id))}catch(reason){setError(reason.message||"A munkamenet visszavonása sikertelen.")}finally{setBusyId("")}};
  return <section className="card active-sessions-card"><span className="eyebrow">BIZTONSÁG</span><h2>Aktív munkamenetek</h2><p>Itt láthatod, mely böngészőkben vagy bejelentkezve. Az ismeretlen eszközöket azonnal kijelentkeztetheted.</p><div className="active-session-list">{sessions.map(session=><article className="active-session-row" key={session.id}><Monitor size={22} aria-hidden="true"/><div><div className="active-session-title"><b>{session.device}</b>{session.current&&<span>EZ AZ ESZKÖZ</span>}</div><small>Utolsó aktivitás: {dateTime(session.lastSeenAt)} · IP: {session.ipHint}</small><small>Lejárat: {dateTime(session.expiresAt)}</small></div>{!session.current&&<button className="danger-outline" disabled={busyId===session.id} onClick={()=>revoke(session)}>{busyId===session.id?"Visszavonás…":"Kijelentkeztetés"}</button>}</article>)}</div>{error&&<p className="auth-error" role="alert">{error}</p>}</section>}

export function DataExportCard(){const [busy,setBusy]=useState(false),[error,setError]=useState(""),[completed,setCompleted]=useState(false);
  const download=async()=>{setBusy(true);setError("");setCompleted(false);try{const response=await fetch("/api/state?export=1",{cache:"no-store",credentials:"same-origin"});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||"Az export nem készíthető el.")}const blob=await response.blob(),filename=(response.headers.get("Content-Disposition")||"").match(/filename="([^"]+)"/i)?.[1]||"hybrid-athlete-adatexport.json",url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setCompleted(true)}catch(reason){setError(reason.message||"Az export nem készíthető el.")}finally{setBusy(false)}};
  return <section className="card data-export-card"><span className="eyebrow">SAJÁT ADATOK</span><h2>Adatok letöltése</h2><p>Töltsd le JSON-formátumban a profilodat, terveidet, állapotfelméréseidet, edzés-visszajelzéseidet, az Edzőtárs memóriáját és a szinkronizált teljesítmény-összesítéseidet.</p><div className="data-export-note"><LockKeyhole size={18} aria-hidden="true"/><span>Az export nem tartalmaz jelszót, munkamenet-cookie-t, titkos Garmin-tokent vagy más felhasználó adatát.</span></div><button className="primary data-export-button" disabled={busy} onClick={download}><Download size={17} aria-hidden="true"/>{busy?"Export készítése…":"Saját adatok letöltése"}</button>{completed&&<p className="auth-success" role="status">Az adatfájl elkészült és letöltődött.</p>}{error&&<p className="auth-error" role="alert">{error}</p>}</section>}

export function PasswordChangeCard({onChanged}){const [currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirmation,setConfirmation]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const submit=async event=>{event.preventDefault();setError("");if(newPassword!==confirmation){setError("Az új jelszó és a megerősítés nem egyezik.");return}setBusy(true);try{const result=await authRequest({action:"change_password",currentPassword,newPassword});onChanged(result.message||"A jelszavad megváltozott. Lépj be újra.")}catch(reason){setError(reason.message||"A jelszó nem módosítható.");setBusy(false)}};
  return <section className="card password-change-card"><span className="eyebrow">FIÓKBIZTONSÁG</span><h2>Jelszó megváltoztatása</h2><p>A módosításhoz add meg a jelenlegi jelszavadat. Sikeres változtatás után minden aktív eszközről kijelentkeztetünk.</p><form onSubmit={submit}><label>Jelenlegi jelszó<input type="password" autoComplete="current-password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)} required maxLength="200"/></label><label>Új jelszó<input type="password" autoComplete="new-password" value={newPassword} onChange={event=>setNewPassword(event.target.value)} required minLength="10" maxLength="200"/><small>Legalább 10 karakter; ne egyezzen a jelenlegi jelszóval.</small></label><label>Új jelszó ismét<input type="password" autoComplete="new-password" value={confirmation} onChange={event=>setConfirmation(event.target.value)} required minLength="10" maxLength="200"/></label>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="primary" disabled={busy}><LockKeyhole size={17} aria-hidden="true"/>{busy?"Jelszó módosítása…":"Jelszó módosítása"}</button></form></section>}

const DELETE_PHRASE="FIÓK TÖRLÉSE";

export function AccountDeletionCard({onDeleted}){const [expanded,setExpanded]=useState(false),[currentPassword,setCurrentPassword]=useState(""),[confirmation,setConfirmation]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const submit=async event=>{event.preventDefault();setError("");setBusy(true);try{const result=await authRequest({action:"delete_account",currentPassword,confirmation});clearLocalPersonalData();onDeleted(result.message||"A fiók és a személyes adatok törlődtek.")}catch(reason){setError(reason.message||"A fiók törlése nem hajtható végre.");setBusy(false)}};
  const cancel=()=>{setExpanded(false);setCurrentPassword("");setConfirmation("");setError("")};
  return <section className="card account-deletion-card"><span className="eyebrow">VESZÉLYZÓNA</span><h2>Fiók és személyes adatok törlése</h2><p>A művelet véglegesen eltávolítja a profilodat, terveidet, állapotfelméréseidet, edzés-visszajelzéseidet, az Edzőtárs memóriáját, a Garmin-kapcsolatodat és a szinkronizált sportadataidat.</p>
    {!expanded?<button className="danger-outline account-deletion-toggle" type="button" aria-expanded="false" onClick={()=>setExpanded(true)}><Trash2 size={17} aria-hidden="true"/> Fiók törlésének előkészítése</button>
    :<div className="account-deletion-confirmation"><div className="account-deletion-warning" role="note"><TriangleAlert size={20} aria-hidden="true"/><div><strong>Ez a művelet nem vonható vissza.</strong><ul><li>Minden aktív munkamenet azonnal megszűnik.</li><li>A Garmin-kapcsolat és minden felhasználói sportadat törlődik.</li><li>Csak egy név és e-mail nélküli anonim azonosító marad meg, hogy a biztonsági napló hitelessége megőrizhető legyen.</li></ul></div></div>
      <form onSubmit={submit}><label>Jelenlegi jelszó<input type="password" autoComplete="current-password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)} required maxLength="200"/></label><label>Megerősítő szöveg<input type="text" autoComplete="off" value={confirmation} onChange={event=>setConfirmation(event.target.value)} required maxLength={DELETE_PHRASE.length} aria-describedby="account-delete-phrase"/><small id="account-delete-phrase">Írd be pontosan: <b>{DELETE_PHRASE}</b></small></label>{error&&<p className="auth-error" role="alert">{error}</p>}<div className="account-deletion-actions"><button type="button" onClick={cancel} disabled={busy}>Mégsem</button><button className="account-delete-final" disabled={busy||!currentPassword||confirmation!==DELETE_PHRASE}><Trash2 size={17} aria-hidden="true"/>{busy?"Fiók törlése…":"Fiók végleges törlése"}</button></div></form></div>}</section>}

const AUDIT_LABELS={invite_created:"Meghívólink létrehozva",invite_revoked:"Meghívó visszavonva",password_reset_created:"Jelszó-visszaállító link létrehozva",user_suspended:"Felhasználó felfüggesztve",user_reactivated:"Felhasználó újraaktiválva"};

export function AdminAccessCard(){const [data,setData]=useState({users:[],invites:[],audit:[]}),[resetEmail,setResetEmail]=useState(""),[generated,setGenerated]=useState(null),[pendingAccessId,setPendingAccessId]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState(false);
  const load=()=>fetch("/api/admin").then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"A hozzáférések nem tölthetők be.");return body}).then(setData).catch(reason=>setError(reason.message));
  useEffect(()=>{load()},[]);
  const act=async payload=>{setBusy(true);setError("");setGenerated(null);setCopied(false);try{const response=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"A művelet sikertelen.");if(body.path)setGenerated({url:`${window.location.origin}${body.path}`,email:body.email||""});await load();setPendingAccessId("")}catch(reason){setError(reason.message)}finally{setBusy(false)}};
  const copy=async()=>{if(generated?.url){await navigator.clipboard?.writeText(generated.url);setCopied(true)}};
  return <section className="card admin-access-card"><span className="eyebrow">ADMINISZTRÁCIÓ</span><h2>Zárt hozzáférés</h2><p>Csak az általad létrehozott, egyszer használható hivatkozással lehet új fiókot nyitni. A link 7 napig érvényes.</p>
    <div className="admin-access-actions"><button className="primary" disabled={busy} onClick={()=>act({action:"create_invite"})}><Plus size={17}/> Új meghívólink</button><div className="admin-reset-row"><input type="email" value={resetEmail} onChange={event=>setResetEmail(event.target.value)} placeholder="Felhasználó e-mail-címe" aria-label="Felhasználó e-mail-címe a jelszólinkhez"/><button disabled={busy||!resetEmail} onClick={()=>act({action:"create_password_reset",email:resetEmail})}>Jelszólink</button></div></div>
    {generated&&<div className="admin-generated-link"><div><b>{generated.email?"Jelszó-visszaállító link":"Meghívólink"}</b><small>Másold ki és küldd el közvetlenül a felhasználónak. Egyszer használható.</small></div><input readOnly value={generated.url} aria-label="Generált hivatkozás"/><button onClick={copy}>{copied?"Másolva":"Másolás"}</button></div>}
    {error&&<p className="auth-error" role="alert">{error}</p>}
    <div className="admin-access-grid"><div><h3>Felhasználók ({data.users.length})</h3>{data.users.map(item=><div className="admin-access-row" key={item.id}><span><b>{item.name}</b><small>{item.email}</small><em>{item.role==="admin"?"ADMIN":item.accessStatus==="suspended"?"FELFÜGGESZTVE":"AKTÍV TAG"}</em></span>{item.role!=="admin"&&item.accessStatus==="suspended"&&<button disabled={busy} onClick={()=>act({action:"set_user_access",id:item.id,status:"active"})}>Újraaktiválás</button>}{item.role!=="admin"&&item.accessStatus!=="suspended"&&pendingAccessId!==item.id&&<button className="danger-outline" disabled={busy} onClick={()=>setPendingAccessId(item.id)}>Felfüggesztés</button>}{pendingAccessId===item.id&&<span className="admin-access-confirm"><button className="danger-outline" disabled={busy} onClick={()=>act({action:"set_user_access",id:item.id,status:"suspended"})}>Biztosan felfüggesztem</button><button disabled={busy} onClick={()=>setPendingAccessId("")}>Mégse</button></span>}</div>)}</div>
      <div><h3>Meghívók</h3>{data.invites.length===0&&<p className="admin-empty">Még nincs létrehozott meghívó.</p>}{data.invites.map(item=><div className="admin-access-row" key={item.id}><span><b>{item.status==="active"?"Aktív":item.status==="used"?"Felhasználva":item.status==="revoked"?"Visszavonva":"Lejárt"}</b><small>{item.usedBy?(/^deleted-.*@invalid\.local$/.test(item.usedBy)?"Törölt felhasználó":item.usedBy):`Lejár: ${dateTime(item.expiresAt)}`}</small></span>{item.status==="active"&&<button className="danger-outline" disabled={busy} onClick={()=>act({action:"revoke_invite",id:item.id})}><Trash2 size={15}/> Visszavonás</button>}</div>)}</div></div>
    {data.aiUsage&&<div className="admin-ai-usage"><div className="admin-audit-heading"><div><h3>AI-használat (30 nap)</h3><p>Összesített, felhasználó nélküli adat. A költség a Claude Sonnet 5.5 listaárával számolt becslés.</p></div><span>{data.aiUsage.questions} KÉRDÉS</span></div><div className="admin-ai-usage-grid"><span><b>{data.aiUsage.questions.toLocaleString("hu-HU")}</b><small>Edzőtárs-kérdés</small></span><span><b>{Math.round(data.aiUsage.tokens/1000).toLocaleString("hu-HU")} e</b><small>Token</small></span><span><b>${data.aiUsage.estimatedCostUsd.toLocaleString("hu-HU",{minimumFractionDigits:2,maximumFractionDigits:2})}</b><small>Becsült költség</small></span><span><b>{data.aiUsage.questions?`$${(data.aiUsage.estimatedCostUsd/data.aiUsage.questions).toLocaleString("hu-HU",{minimumFractionDigits:3,maximumFractionDigits:3})}`:"—"}</b><small>Átlag / kérdés</small></span></div></div>}
    <div className="admin-audit"><div className="admin-audit-heading"><div><h3>Adminisztrátori napló</h3><p>A hozzáférést érintő műveletek időpontja és végrehajtója. A titkos linkeket és tokeneket nem tároljuk itt.</p></div><span>{data.audit?.length||0} BEJEGYZÉS</span></div>{!data.audit?.length&&<p className="admin-empty">Még nincs naplózott adminisztrátori művelet.</p>}<div className="admin-audit-list">{(data.audit||[]).map(item=><div className="admin-audit-row" key={item.id}><span><b>{AUDIT_LABELS[item.action]||"Adminisztrátori művelet"}</b>{item.target&&<small>Érintett fiók: {item.target}</small>}</span><span><b>{dateTime(item.createdAt)}</b><small>Végrehajtotta: {item.actor}</small></span></div>)}</div></div></section>}
