import { useEffect, useRef, useState } from "react";
import { Brain, CalendarCheck, MessageCircle, RotateCcw, Send, ShieldCheck, Trash2, X } from "lucide-react";

const STARTERS=["Mit eddzek holnap?","Mire figyeljek a héten?","Hogyan javíthatom a VO2max-omat?","Mit jelent a mai readiness-em?"];

async function assistantRequest(payload){const response=await fetch("/api/assistant",{method:payload?"POST":"GET",headers:payload?{"Content-Type":"application/json"}:undefined,body:payload?JSON.stringify(payload):undefined}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Az edzőtárs most nem érhető el.");return body}

// Minimal, safe rendering of the model's markdown: paragraphs, "- " bullets and **bold**, no HTML injection.
function RichText({text}){const blocks=String(text||"").split(/\n{2,}/);const inline=line=>line.split(/(\*\*[^*]+\*\*)/g).map((part,index)=>part.startsWith("**")&&part.endsWith("**")?<b key={index}>{part.slice(2,-2)}</b>:part);return blocks.map((block,index)=>{const lines=block.split("\n").filter(Boolean);if(lines.length&&lines.every(line=>/^\s*[-•]\s+/.test(line)))return <ul key={index}>{lines.map((line,item)=><li key={item}>{inline(line.replace(/^\s*[-•]\s+/,""))}</li>)}</ul>;return <p key={index}>{lines.map((line,item)=><span key={item}>{item>0&&<br/>}{/^\s*[-•]\s+/.test(line)?<>• {inline(line.replace(/^\s*[-•]\s+/,""))}</>:inline(line.replace(/^#+\s*/,""))}</span>)}</p>})}

const STATUS_LABEL={pending:"Jóváhagyásra vár",applied:"Bekerült a Naptárba",rejected:"Elutasítva",expired:"Lejárt",applying:"Mentés folyamatban"};
const planLine=plan=>plan?`${new Date(`${plan.date}T12:00:00`).toLocaleDateString("hu-HU",{month:"short",day:"numeric"})} (${new Date(`${plan.date}T12:00:00`).toLocaleDateString("hu-HU",{weekday:"long"})}) · ${plan.type} · ${plan.title} · ${plan.duration} perc · ${plan.intensity} · RPE ${plan.rpe}`:"";

// A proposed plan change is only a preview until the athlete approves it here.
function ProposalCard({action,busy,onDecide}){const before=action.before,removing=action.action==="delete_plan";return <div className={`assistant-proposal ${action.status}`}><div className="assistant-proposal-head"><CalendarCheck size={16} aria-hidden="true"/><b>{action.summary}</b><span>{STATUS_LABEL[action.status]||action.status}</span></div>{removing?<p><small>Törlendő</small>{planLine(before)}</p>:<>{before&&<p className="was"><small>Jelenleg</small>{planLine(before)}</p>}<p><small>{before?"Javasolt":"Új edzés"}</small>{planLine(action.plan)}</p></>}{action.reason&&<p className="assistant-proposal-reason">{action.reason}</p>}{action.status==="pending"&&<div className="assistant-proposal-actions"><button className="primary" disabled={busy} onClick={()=>onDecide(action.id,"approve")}>Jóváhagyom</button><button disabled={busy} onClick={()=>onDecide(action.id,"reject")}>Elutasítom</button></div>}</div>}

export function AssistantPanel({onPlansChanged}){const [open,setOpen]=useState(false),[state,setState]=useState(null),[question,setQuestion]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[showMemory,setShowMemory]=useState(false),listRef=useRef(null);
  useEffect(()=>{if(open&&!state)assistantRequest().then(setState).catch(reason=>setError(reason.message))},[open]);
  useEffect(()=>{listRef.current?.scrollTo?.({top:listRef.current.scrollHeight})},[state?.conversation?.length,busy]);
  const run=async payload=>{setError("");try{setState(await assistantRequest(payload))}catch(reason){setError(reason.message)}};
  const send=async text=>{const value=(text??question).trim();if(!value||busy)return;setBusy(true);setError("");setQuestion("");setState(current=>current&&{...current,conversation:[...current.conversation,{role:"user",content:value,pending:true}]});try{setState(await assistantRequest({action:"ask",question:value}))}catch(reason){setError(reason.message);setQuestion(value);setState(current=>current&&{...current,conversation:current.conversation.filter(item=>!item.pending)})}finally{setBusy(false)}};
  const decide=async(id,decision)=>{setBusy(true);setError("");try{const next=await assistantRequest({action:"decideProposal",id,decision});setState(next);if(next.decision?.status==="applied")await onPlansChanged?.()}catch(reason){setError(reason.message);run()}finally{setBusy(false)}};
  const usage=state?.usage,conversation=state?.conversation||[];
  if(!open)return <button className="assistant-launcher" onClick={()=>setOpen(true)} aria-label="Edzőtárs megnyitása"><MessageCircle size={20}/><span>Edzőtárs</span></button>;
  return <aside className="assistant-panel" aria-label="AI edzőtárs"><div className="assistant-head"><div><b>Edzőtárs</b><small>{usage?`Ma még ${usage.remaining}/${usage.limit} kérdés${usage.tokenUsedPct>=50?` · napi keret ${usage.tokenUsedPct}%-a felhasználva`:""}`:"Betöltés…"}</small></div><div className="assistant-head-actions">{state?.consent&&<><button onClick={()=>setShowMemory(value=>!value)} aria-pressed={showMemory} title="Memória"><Brain size={17}/></button><button onClick={()=>run({action:"resetConversation"})} title="Új beszélgetés" disabled={!conversation.length}><RotateCcw size={17}/></button></>}<button onClick={()=>setOpen(false)} aria-label="Bezárás"><X size={18}/></button></div></div>
    {state&&!state.consent?<div className="assistant-consent"><ShieldCheck size={26}/><h3>Mielőtt kérdezel</h3><p>Az edzőtárs egy mesterséges intelligencia (Anthropic Claude). A válaszokhoz az alkalmazás az edzésadataidból számolt <b>összesített</b> értékeket (pl. readiness, terhelés, alvás, korosztályos összevetés) és a kérdéseidet küldi el. Nyers Garmin-adat, jelszó és e-mail-cím nem kerül át.</p><p>A beszélgetésből rövid emlékeztetőket menthetünk (pl. preferenciák, panaszok), hogy személyre szabottabb legyen. Ezeket bármikor megnézheted és törölheted; a hozzájárulás visszavonásával minden törlődik.</p><p className="assistant-note">Sportteljesítményi támogatás, nem orvosi tanácsadás.</p><button className="primary" onClick={()=>run({action:"consent",value:true})}>Elfogadom és kezdhetjük</button></div>
    :showMemory&&state?<div className="assistant-memory"><div className="assistant-memory-head"><b>Amit megjegyeztem rólad</b><label><input type="checkbox" checked={state.memoryEnabled} onChange={event=>run({action:"memory",enabled:event.target.checked})}/> Memória bekapcsolva</label></div>{state.memory.length?<ul>{state.memory.map(item=><li key={item.id}><span>{item.text}</span><button onClick={()=>run({action:"deleteMemory",id:item.id})} aria-label={`Törlés: ${item.text}`}><Trash2 size={15}/></button></li>)}</ul>:<p className="assistant-note">Még nincs mentett emlékeztető.</p>}<div className="assistant-memory-actions">{state.memory.length>0&&<button className="danger-outline" onClick={()=>run({action:"deleteMemory",all:true})}>Összes törlése</button>}<button className="danger-outline" onClick={()=>{run({action:"consent",value:false});setShowMemory(false)}}>Hozzájárulás visszavonása</button></div></div>
    :<><div className="assistant-messages" ref={listRef}>{!conversation.length&&<div className="assistant-empty"><p>Kérdezz bármit az edzéseidről, a mai állapotodról vagy a céljaidról. A válaszok a saját Garmin-adataidra épülnek.</p><div className="assistant-starters">{STARTERS.map(item=><button key={item} onClick={()=>send(item)} disabled={busy||!state}>{item}</button>)}</div></div>}{conversation.map((item,index)=><div key={index} className={`assistant-message ${item.role}`}>{item.role==="assistant"?<RichText text={item.content}/>:<p>{item.content}</p>}{item.actions?.map(action=><ProposalCard key={action.id} action={action} busy={busy} onDecide={decide}/>)}</div>)}{busy&&<div className="assistant-message assistant typing" role="status">Gondolkodom…</div>}</div>
      <form className="assistant-input" onSubmit={event=>{event.preventDefault();send()}}><textarea value={question} onChange={event=>setQuestion(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();send()}}} placeholder="Írd ide a kérdésed…" rows={2} maxLength={1500} disabled={busy||!state||usage?.remaining===0} aria-label="Kérdés az edzőtársnak"/><button className="primary" disabled={busy||!question.trim()||usage?.remaining===0} aria-label="Küldés"><Send size={17}/></button></form>
      <p className="assistant-footnote">AI által generált válasz, tévedhet. Nem orvosi tanácsadás. Edzéstervet csak a jóváhagyásoddal módosít.</p></>}
    {error&&<p className="auth-error assistant-error" role="alert">{error}</p>}</aside>}
