import { useEffect } from "react";
import brandMarkUrl from "../assets/hybrid-athlete-mark-on-dark.svg";

function BrandMark({className=""}){return <img className={`brand-mark ${className}`} src={brandMarkUrl} alt="" aria-hidden="true"/>}
export function BrandLogo({compact=false}){return <div className={`brand-logo ${compact?"compact":""}`} aria-label="Hybrid Athlete"><span className="brand-logo-mark"><BrandMark/></span>{!compact&&<span className="brand-logo-copy"><strong>HYBRID ATHLETE</strong><small>SZEMÉLYES EDZÉSDÖNTÉS</small></span>}</div>}
export function AnimatedBrandMark({mode="running",className=""}){const assembling=mode==="assembling";return <svg className={`animated-brand-mark ${assembling?"assembling":"running"} ${className}`} viewBox={assembling?"0 0 40 30":"-30 0 76 34"} role="img" aria-label={assembling?"A Hybrid Athlete logó összeáll":"A Hybrid Athlete szinkronizál"}>
  {!assembling&&<><g className="ha-wind ha-wind-teal" stroke="var(--accent)" strokeLinecap="round" fill="none"><path d="M-4 7.5 H6" strokeWidth="2.4" opacity=".85"/><path d="M-8 12 H4" strokeWidth="2.8"/><path d="M-6 16.5 H8" strokeWidth="2.2" opacity=".7"/><path d="M-10 21 H2" strokeWidth="2.6" opacity=".9"/><path d="M-4 25.5 H6" strokeWidth="2" opacity=".55"/></g><g className="ha-wind ha-wind-white" stroke="rgba(255,255,255,.55)" strokeLinecap="round" fill="none"><path d="M-2 10 H5" strokeWidth="1.1"/><path d="M-5 19 H3" strokeWidth="1.1"/></g></>}
  <g className={assembling?"ha-assemble-body":"ha-run-body"}><path className={assembling?"ha-asm-left":"ha-run-leg-a"} d="M11 28 L16 2 H21 L16 28 Z" fill="currentColor"/><path className={assembling?"ha-asm-right":"ha-run-leg-b"} d="M28 28 L33 2 H38 L33 28 Z" fill="currentColor"/><path className={assembling?"ha-asm-bar":"ha-run-bar"} d="M15.6 18.6 L33.4 9.4 L34.8 14.6 L17 23.8 Z" fill="var(--accent)"/><rect className={assembling?"ha-asm-dash-1":""} x="0" y="9.6" width="9" height="3.4" rx="1.7" fill="var(--accent)" opacity={assembling?undefined:".55"}/><rect className={assembling?"ha-asm-dash-2":""} x="4" y="16.4" width="6" height="3.4" rx="1.7" fill="var(--accent)" opacity={assembling?undefined:".3"}/></g>
  {!assembling&&<g className="ha-ground" stroke="rgba(255,255,255,.16)" strokeWidth="1.4" strokeLinecap="round"><path d="M6 31 H18"/><path d="M28 31 H40"/><path d="M50 31 H62"/><path d="M72 31 H84"/></g>}
</svg>}
export function BrandSplash({onDone}){useEffect(()=>{const reduce=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches,timer=setTimeout(onDone,reduce?250:4200);return()=>clearTimeout(timer)},[onDone]);return <div className="brand-splash" role="status" aria-live="polite"><div className="brand-splash-lockup"><AnimatedBrandMark mode="assembling"/><strong>HYBRID ATHLETE</strong><span>SZEMÉLYES EDZÉSDÖNTÉS</span></div></div>}
export const splashWasShown=()=>globalThis.sessionStorage?.getItem("hybrid-splash-shown")==="1";
export const forceSplashPreview=()=>new URLSearchParams(globalThis.window?.location?.search||"").get("splash")==="1";
