import { useEffect } from "react";
import { metricGlossary } from "../lib/glossary.js";

export function MetricHelp({term,children,text}){const explanation=text||metricGlossary[term];if(!explanation)return children;return <span className="metric-help" tabIndex="0" aria-label={`${term}. ${explanation}`}>{children}<span className="metric-tooltip" role="tooltip"><b>{term}</b><span>{explanation}</span></span></span>}
function explanationTerm(text){const value=String(text||"").toUpperCase();if(value.includes("CTL")&&value.includes("ATL")&&value.includes("TSB"))return "CTL · ATL · TSB";if(value.includes("CTL"))return "CTL";if(value.includes("ATL"))return "ATL";if(value.includes("TSB"))return "TSB";if(value.includes("HRV"))return "HRV (éjszakai)";if(value.includes("ALVÁS"))return "Alvás";if(value.includes("RPE"))return "RPE";if(value.includes("PULZUS")||value.includes("BPM"))return "Pulzus";if(/\bZ[1-5]\b/.test(value)||value.includes("ZÓNA"))return "Pulzuszóna";if(value.includes("TÁV")||value.includes(" KM"))return "Táv";if(value.includes("ERŐ"))return "Erő arány";if(value.includes("EDZÉS / HÉT"))return "Edzésgyakoriság";if(value.includes("IDŐKERET")||value.includes("EDZÉSIDŐ")||value.includes("PERC")||value.includes("ÓRA"))return "Edzésidő";if(value.includes("BIZONYOSSÁG"))return "Bizonyosság";if(value.includes("READINESS")||value.includes("FELKÉSZÜLTSÉG"))return "Felkészültség";if(value.includes("TERHELÉS")||value.includes("LOAD"))return "Terhelés";return null}
// Runs an idempotent DOM decoration pass on page change and again whenever content is added later
// (e.g. a page that first shows a gate or a loading state, then its real KPIs).
function useDomPass(run,page){useEffect(()=>{let timer=setTimeout(run,0);const observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(run,0)});observer.observe(document.body,{childList:true,subtree:true});return()=>{clearTimeout(timer);observer.disconnect()}},[page])}
export function ExplainabilityLayer({page}){useDomPass(()=>{const selectors=[".ring",".heatmap",".weekbar",".week-stats>div",".trend-summary .card",".zone-row",".goal-progress",".goal-score",".goal-component",".goal-meta span",".finding-score",".weekly-recap>div>span",".activity-stats>span",".plan-comparison",".calendar-grid>button>div",".table-wrap tbody td:nth-child(4)",".table-wrap tbody td:nth-child(5)",".table-wrap tbody td:nth-child(6)",".table-wrap tbody td:nth-child(7)",".table-wrap tbody td:nth-child(8)"];document.querySelectorAll(selectors.join(",")).forEach(node=>{if(node.closest(".metric-help")||node.hasAttribute("aria-expanded"))return;let term=explanationTerm(node.textContent);if(!term&&node.matches(".ring"))term="Readiness";if(!term&&node.matches(".heatmap"))term="Terhelés";if(!term&&node.matches(".weekbar"))term="Időkeret";if(!term&&node.matches(".goal-score,.goal-component"))term="Felkészültség";if(!term&&node.matches(".finding-score"))term="Bizonyosság";if(!term&&node.matches(".calendar-grid>button>div,.table-wrap tbody td:nth-child(4)"))term="Edzésidő";if(!term&&node.matches(".table-wrap tbody td:nth-child(5)"))term="Pulzus";if(!term&&node.matches(".table-wrap tbody td:nth-child(6)"))term="Táv";if(!term&&node.matches(".table-wrap tbody td:nth-child(7)"))term="Terhelés";if(!term&&node.matches(".table-wrap tbody td:nth-child(8)"))term="RPE";if(term&&metricGlossary[term]){node.classList.add("explained-value");node.tabIndex=node.tabIndex>=0?node.tabIndex:0;node.dataset.metric=term;node.dataset.explanation=metricGlossary[term];node.setAttribute("aria-label",`${node.textContent.trim()}. ${term}: ${metricGlossary[term]}`)}})},page);return null}
export function MetricHeaderLayer({page}){useDomPass(()=>{const headers=[[".table-wrap th:nth-child(4)","Edzésidő"],[".table-wrap th:nth-child(5)","Pulzus"],[".table-wrap th:nth-child(6)","Táv"],[".table-wrap th:nth-child(7)","Terhelés"],[".table-wrap th:nth-child(8)","RPE"],[".chart-card .section-head .eyebrow","CTL · ATL · TSB"]];headers.forEach(([selector,term])=>document.querySelectorAll(selector).forEach(node=>{if(!metricGlossary[term])return;node.classList.add("explained-value","metric-header-explanation");node.tabIndex=0;node.dataset.metric=term;node.dataset.explanation=metricGlossary[term];node.setAttribute("aria-label",`${node.textContent.trim()}. ${term}: ${metricGlossary[term]}`)}))},page);return null}
