import { useEffect, useState } from "react";
import { Activity, LockKeyhole } from "lucide-react";

const STATUS_LABEL={connected:"CSATLAKOZTATVA",mfa_required:"ELLENŐRZÉS SZÜKSÉGES",reauth_required:"ÚJRACSATLAKOZTATÁS"};

// The Garmin password is only used for the login request; the server keeps an encrypted session token.
export function GarminConnectionCard({onStatus}){const [status,setLocalStatus]=useState(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[mfaCode,setMfaCode]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),setStatus=value=>{setLocalStatus(value);onStatus?.(value)};
  useEffect(()=>{fetch("/api/garmin").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setStatus(body)}).catch(reason=>setError(reason.message||"A kapcsolat állapota nem tölthető be."))},[]);
  const call=async(method,payload,after)=>{setBusy(true);setError("");try{const response=await fetch("/api/garmin",{method,headers:payload?{"Content-Type":"application/json"}:undefined,body:payload?JSON.stringify(payload):undefined}),body=await response.json();if(!response.ok)throw new Error(body.error);setStatus(body);after?.(body)}catch(reason){setError(reason.message)}finally{setBusy(false)}};
  const connect=event=>{event.preventDefault();call("POST",{email,password},body=>{if(body.status==="connected"){setPassword("");setMfaCode("")}})};
  const verifyMfa=event=>{event.preventDefault();call("POST",{action:"verify_mfa",code:mfaCode},()=>{setPassword("");setMfaCode("")})};
  const disconnect=()=>call("DELETE",null,()=>{setEmail("");setPassword("")});
  const state=status?.status;
  return <section className="card garmin-connection"><span className="eyebrow">ADATFORRÁS</span><div className="connection-heading"><div><h2>Garmin Connect</h2><p>A saját Garmin-előzményeid csak a te fiókodhoz kerülnek.</p></div><span className={state==="connected"?"connected":"disconnected"}>{STATUS_LABEL[state]||"NINCS KAPCSOLAT"}</span></div>
    {state==="connected"?<><div className="connected-account"><Activity size={22}/><div><b>{status.email_hint}</b><small>A Garmin-munkamenet titkosítva van tárolva; Garmin-jelszót nem őrzünk meg.</small></div></div><div className="connection-actions"><button className="danger-outline" disabled={busy} onClick={disconnect}>Garmin leválasztása</button></div><p className="connection-retention-note">A leválasztás a titkosított Garmin-munkamenetet törli. A már szinkronizált előzmények és összesítések ettől még megmaradnak a fiókodban.</p></>
    :state==="mfa_required"?<form onSubmit={verifyMfa}><label>Egyszer használatos Garmin-kód<input type="text" inputMode="numeric" autoComplete="one-time-code" value={mfaCode} onChange={event=>setMfaCode(event.target.value)} required autoFocus/></label><p className="connection-note"><LockKeyhole size={15}/> A Garmin által e-mailben vagy SMS-ben küldött kódot add meg. A munkamenet 10 percig folytatható.</p><button className="primary" disabled={busy}>{busy?"Ellenőrzés…":"Kód ellenőrzése"}</button></form>
    :<form onSubmit={connect}>{state==="reauth_required"&&<p className="connection-note">A Garmin-munkamenet lejárt vagy hiányzik, ezért egyszer újra be kell jelentkezned.</p>}<label>Garmin e-mail-cím<input type="email" autoComplete="username" value={email} onChange={event=>setEmail(event.target.value)} required/></label><label>Garmin-jelszó<input type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} required/></label><p className="connection-note"><LockKeyhole size={15}/> A jelszót csak a Garmin-hitelesítéshez használjuk, nem tároljuk. Sikeres belépés után kizárólag a titkosított munkamenettoken marad meg. Kétlépcsős azonosításnál a következő lépésben kérjük a kódot.</p><button className="primary" disabled={busy}>{busy?"Csatlakoztatás…":"Garmin csatlakoztatása"}</button></form>}
    {error&&<p className="auth-error" role="alert">{error}</p>}</section>}
