import { useEffect, useState } from "react";
import { LockKeyhole, RefreshCw, TrendingUp } from "lucide-react";

// Status of the per-user recovery model maintained by the daily /api/retrain cron.
// Only sample size, data window and plainly explained error reach the browser — never coefficients or raw Garmin data.
function useModelStatus(){const [state,setState]=useState({status:"loading",data:null});useEffect(()=>{let active=true;fetch("/api/model",{cache:"no-store"}).then(async response=>{const value=await response.json();if(!response.ok||!value||typeof value!=="object"||!("active" in value)||!("lastRun" in value))throw new Error("model-status-unavailable");if(active)setState({status:"ready",data:value})}).catch(()=>{if(active)setState({status:"unavailable",data:null})});return()=>{active=false}},[]);return state}

const day=value=>value?new Date(`${value}T12:00:00`).toLocaleDateString("hu-HU"):"ismeretlen dátum";
const moment=value=>value?new Date(value).toLocaleString("hu-HU",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}):"a következő napi futáskor";
const decimal=(value,digits)=>Number(value).toLocaleString("hu-HU",{minimumFractionDigits:digits,maximumFractionDigits:digits});

export function ModelStatusCard(){const {status,data}=useModelStatus(),active=data?.active,lastRun=data?.lastRun,readiness=data?.readiness,schedule=data?.schedule;
  const title=status==="loading"?"Modellállapot betöltése":status==="unavailable"?"A modellállapot most nem érhető el":active?"Aktív személyes regenerációs modell":lastRun?.status==="insufficient"?"Még gyűjtjük a szükséges előzményt":"A személyes modell előkészítés alatt áll";
  const message=status==="unavailable"?"A többi elemzés továbbra is használható. A háttérellenőrzés állapotát később újra lekérjük.":active?`${active.samples} érvényes nap alapján, ${day(active.data_start)} és ${day(active.data_end)} között. Az átlagos abszolút hiba ${decimal(active.model_mae,2)} a belső, standardizált következő napi regenerációs indexen. Ez nem terhelhetőségi pontszám: az alacsonyabb hiba pontosabb előrejelzést jelent.`:lastRun?.message||"A rendszer naponta ellenőrzi, hogy rendelkezésre áll-e elég jó minőségű adat. Gyengébb jelöltet nem aktivál automatikusan.";
  const improvement=active?.validation?.improvementPct??(active?.baseline_mae>0?(active.baseline_mae-active.model_mae)/active.baseline_mae*100:null),windows=active?.validation,remaining=readiness?Math.max(0,Number(readiness.requiredSamples||132)-Number(readiness.availableSamples||0)):null,progress=Math.max(0,Math.min(100,Number(readiness?.progressPct||0)));
  return <section className="card model-status" aria-live="polite"><div className="model-status-heading">{status==="loading"?<RefreshCw className="model-status-spinner" size={19}/>:active?<TrendingUp size={19}/>:<LockKeyhole size={19}/>}<div><span className="eyebrow">SZEMÉLYES MODELL</span><b>{title}</b></div>{status==="ready"&&<span className={`model-status-pill ${active?"active":"preparing"}`}>{active?"AKTÍV":"ELŐKÉSZÍTÉS"}</span>}</div><p className="model-status-summary">{status==="loading"?"":message}</p>
    {status==="ready"&&readiness&&<div className="model-data-readiness"><div className="model-progress-label"><span>Értékelhető előzmény</span><strong>{readiness.availableSamples} / {readiness.requiredSamples} nap</strong></div><span className="model-progress-track" role="progressbar" aria-label="A személyes modellhez felhasználható előzmény" aria-valuemin="0" aria-valuemax={readiness.requiredSamples} aria-valuenow={Math.min(readiness.availableSamples,readiness.requiredSamples)}><i style={{width:`${progress}%`}}/></span><p>{remaining>0?`Még ${remaining} értékelhető nap szükséges az első modelljelölt vizsgálatához.`:"Megvan a minimális előzmény. Ez még nem jelent automatikus aktiválást: a jelöltnek három időrendi tesztből legalább kettőben jobbnak kell lennie az egyszerű viszonyítási alapnál."}</p></div>}
    {active&&<div className="model-validation-grid"><div><span>VISZONYÍTÁSI ALAPHOZ KÉPEST</span><strong>{improvement!=null&&Number.isFinite(Number(improvement))?`${Number(improvement).toLocaleString("hu-HU",{maximumFractionDigits:1})}% kisebb hiba`:"Érvényesített"}</strong><p>Az egyszerű, személyre nem szabott becsléshez viszonyított eredmény.</p></div><div><span>IDŐRENDI TESZTABLAKOK</span><strong>{windows?.windowCount?`${windows.windowsWon} / ${windows.windowCount} jobb`:"Legalább 2 / 3 jobb"}</strong><p>A régebbi adatokon tanul, majd későbbi, addig nem látott napokon vizsgázik.</p></div></div>}
    {status==="ready"&&readiness?.coverage?.length>0&&<div className="model-coverage"><span>ADATLEFEDETTSÉG</span><div>{readiness.coverage.map(item=><span key={item.key}><b>{item.label}</b><small>{item.coveragePct}%</small></span>)}</div><p>A lefedettség azt mutatja, az összes megfigyelt nap mekkora részén volt jelen az adott adat. A hiányzó érték nem számít nullának.</p></div>}
    {lastRun?.reasons?.length>0&&!active&&<div className="model-reasons"><span>MIÉRT VÁR MÉG?</span><ul>{lastRun.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></div>}
    <div className="model-status-timing">{lastRun?.checkedAt&&<small>Utolsó ellenőrzés: {moment(lastRun.checkedAt)}</small>}{schedule?.nextCheckAt&&<small>Következő automatikus ellenőrzés: {moment(schedule.nextCheckAt)}</small>}</div></section>}
