import { useState } from "react";
import { Activity, ChevronDown } from "lucide-react";
import { MetricHelp } from "./Explainability.jsx";
import { metrics } from "../lib/demoData.js";

function metricImpact(name,score){const level=score>=75?"kedvező":score>=55?"elfogadható":"óvatosságot indokol";if(name.includes("HRV"))return `A személyes alapértékedhez viszonyított állapot ${level}. Tartós romlásnál érdemes csökkenteni az intenzitást.`;if(name.includes("Alvás"))return `Az alvásból számolt regeneráció ${level}. Gyengébb értéknél a technika és a könnyebb aerob munka biztonságosabb választás.`;if(name.includes("pulzus"))return `A nyugalmi pulzusból származó jel ${level}. Szokatlan emelkedés esetén figyeld a fáradtságot és a betegségérzetet.`;return `A rövid és hosszú távú terhelés egyensúlya ${level}. Negatívabb állapot több pihenést, pozitívabb állapot nagyobb frissességet jelezhet.`}
function ReadinessMetric({row,data}){const [name,value,delta,width,tone]=row,[open,setOpen]=useState(false),quality=data?.source==="garmin"?`${(data?.confidence||"közepes").toLowerCase()} bizonyosságú Garmin-adat`:"bemutató adat – saját szinkron után válik személyessé",term=name.includes("TSB")?"TSB":name;return <div className={`metric-wrap ${open?"open":""}`}><button className="metric" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><span className={`metric-icon ${tone}`}><Activity size={15}/></span><b>{name}</b><strong>{value}</strong><span className="bar" aria-label={`${name} hozzájárulási pontszáma: ${Math.round(width)} / 100`}><i style={{width:`${Math.max(0,Math.min(100,width))}%`}}/></span><em>{delta}</em><ChevronDown size={14}/></button>{open&&<div className="metric-detail"><div><span>MIT JELENT MOST?</span><p>{metricImpact(name,width)}</p></div><div><span>ADATMINŐSÉG</span><p>{quality}. A sáv a readinesshez való 0–100-as kedvező hozzájárulást mutatja, nem önálló egészségügyi minősítés.</p></div><div><span>GYAKORLATI KÖVETKEZMÉNY</span><p>{width<55?"A mai tervben válassz kisebb intenzitást, és a saját közérzeted legyen az elsődleges.":width<75?"Az edzés elvégezhető, de ne növeld egyszerre az időtartamot és az intenzitást.":"Ez a jel jelenleg nem korlátozza érdemben a terhelést, ha a többi összetevő és a közérzeted is rendben van."}</p></div><MetricHelp term={term}>Részletes fogalommagyarázat</MetricHelp></div>}</div>}
const HRV_STATUS={BALANCED:"kiegyensúlyozott",UNBALANCED:"kiegyensúlyozatlan",LOW:"alacsony",POOR:"gyenge"};
const shortDate=value=>{const date=new Date(`${value}T12:00:00`);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("hu-HU",{year:"numeric",month:"short",day:"numeric"}).format(date)};

// What the readiness is built on: missing data is listed, never shown as zero.
export function DataCoverage({data}){const quality=data?.dataQuality;if(!quality||data?.source!=="garmin")return null;
  const missing=quality.missingMetrics||[],signals=4-missing.length,official=data.readinessSource==="garmin_training_readiness",tr=data.garminTrainingReadiness,status=HRV_STATUS[String(quality.hrvStatus||"").toUpperCase()],
    hasBaseline=quality.hrvBaselineLow!=null&&quality.hrvBaselineHigh!=null,coverage=quality.officialLoadCoveragePct;
  const rows=[
    ["Readiness forrása",official?`Garmin Training Readiness · ${Math.round(tr?.score??data.readiness)} / 100`:"Hybrid Athlete-becslés",official?"A Garmin óra saját reggeli felkészültségi pontszáma; az edzésjavaslatot erre építve, saját óvatossági szabályainkkal adjuk.":"Az órád ma nem adott Training Readiness pontszámot, ezért a HRV-ből, alvásból, nyugalmi pulzusból és terhelésből saját becslést számolunk.",official?"good":"mixed"],
    ["HRV-állapot",status?`${status}${hasBaseline?` · alapsáv ${Math.round(quality.hrvBaselineLow)}–${Math.round(quality.hrvBaselineHigh)} ms`:""}`:"nincs Garmin-értékelés",status?"A Garmin a saját, többhetes HRV-alapsávodhoz hasonlítja az éjszakai átlagot.":"A HRV-állapothoz az órának néhány hét folyamatos éjszakai mérése kell.",status?"good":"limited"],
    ["Napi állapotjelek",`${signals} / 4 elérhető`,missing.length?`Hiányzik: ${missing.join(", ")}. A hiányzó adat nem nulla; a meglévő jelek súlya arányosan nő.`:"A HRV, az alvás, a nyugalmi pulzus és a hibrid TSB mind rendelkezésre áll.",missing.length?"limited":"good"],
    ["Edzésterhelés forrása",coverage==null?"nincs edzés a héten":`${Math.round(coverage)}% Garmin-adat`,coverage==null?"Terhelési lefedettség csak rögzített edzéseknél számítható.":coverage>=100?"Minden heti edzéshez a Garmin által számolt aktivitási terhelést használjuk.":coverage<=0?"A heti edzésekhez az óra nem adott terhelési értéket, ezért külön jelölt Hybrid Athlete-becslést használunk.":`A fennmaradó ${100-Math.round(coverage)}%-nál külön jelölt Hybrid Athlete-becslés egészíti ki az összesítést.`,coverage>=100?"good":"mixed"],
    ["Előzmény",quality.activityCount?`${Number(quality.activityCount).toLocaleString("hu-HU")} edzés`:"nincs edzés",quality.activityDateFrom?`${shortDate(quality.activityDateFrom)} – ${shortDate(quality.activityDateTo)} A hosszabb előtörténet stabilabb személyes viszonyítási alapot ad.`:"A személyes alapértékekhez néhány hét adat kell.",quality.activityCount?"good":"limited"],
  ];
  return <div className="data-coverage" aria-label="Adatlefedettség"><span className="eyebrow">MIRE ÉPÜL A MAI ÉRTÉKELÉS?</span><div className="data-coverage-grid">{rows.map(([label,value,text,state])=><article key={label} data-state={state}><span>{label}</span><strong>{value}</strong><p>{text}</p></article>)}</div></div>}

export function MetricList({data}){const rows=data?.metrics?.length?data.metrics.map(x=>[x.name,x.value,x.score==null?"nem pontozott":"",x.score??0,x.tone==="good"?"good":"warn"]):metrics;return <section className="card metric-card"><div className="section-head"><MetricHelp term="Readiness"><span className="eyebrow">READINESS ÖSSZETEVŐK</span></MetricHelp><small>{data?.source==="garmin"?`${rows.length} MÉRŐSZÁM · ${data?.readinessSource==="garmin_training_readiness"?"GARMIN TRAINING READINESS":`${(data?.confidence||"KÖZEPES").toUpperCase()} BIZONYOSSÁG`}`:`${rows.length} DEMO MÉRŐSZÁM`}</small></div>{rows.map(row=><ReadinessMetric key={row[0]} row={row} data={data}/>)}<DataCoverage data={data}/></section>}
