import { LockKeyhole, RefreshCw } from "lucide-react";
import { useGarminSync } from "../lib/useGarminSync.js";
import { AnimatedBrandMark } from "./Brand.jsx";
import { GarminConnectionCard } from "./GarminConnectionCard.jsx";
import { PageHeader } from "./PageHeader.jsx";

export const DATA_PAGES=["Áttekintés","Ma","Naptár","Trendek","Cél","Insights","Hol tartasz?","Napló"];

// Shown instead of the data-derived pages until the account has a first synced dataset.
export function SyncGate({garminStatus,onGarminStatus,onDataChanged}){const connected=garminStatus?.status==="connected",{syncing,job,error,start,resumeRunId}=useGarminSync({onCompleted:onDataChanged});return <><PageHeader eyebrow="ELSŐ LÉPÉS" title="Első Garmin-szinkron"/><section className="card sync-gate"><div className="sync-gate-intro"><LockKeyhole size={24}/><div><h2>Az adatokra épülő nézetek a szinkron után nyílnak meg</h2><p>A mai döntés, a Naptár, a Trendek, a Cél, az Insights, a „Hol tartasz?” és a Napló a Garmin-előzményeidből számol. Saját adatok nélkül ezek nem a te állapotodat mutatnák, ezért az első teljes szinkronig zárolva vannak. A Profil és a Beállítások addig is elérhető.</p></div></div><ol className="sync-gate-steps"><li className={connected?"done":"current"}><b>1. Garmin-fiók csatlakoztatása</b><span>{connected?`Csatlakoztatva: ${garminStatus.email_hint}`:"Add meg lent a Garmin Connect belépési adataidat."}</span></li><li className={connected?"current":""}><b>2. Teljes előzmény szinkronizálása</b><span>Az első szinkron a teljes előzménytől függően néhány percig is tarthat; közben bezárhatod az oldalt, és később innen folytatódik.</span></li></ol><div className="sync-gate-action"><button className="primary" disabled={!connected||syncing} onClick={()=>start(resumeRunId)}>{syncing?<AnimatedBrandMark className="sync-brand-mark"/>:<RefreshCw size={16}/>} {syncing?`Szinkronizálás… ${Math.round(job?.progress||0)}%`:resumeRunId?"Szinkron folytatása":"Szinkron indítása"}</button>{!connected&&<small>A szinkronhoz előbb csatlakoztasd a Garmin-fiókodat.</small>}</div>{syncing&&job&&<section className="sync-progress" role="status" aria-live="polite"><div><AnimatedBrandMark/><span><b>Teljes Garmin-előzmény szinkronizálása</b><small>{job.message}</small></span><strong>{Math.round(job.progress||0)}%</strong></div><progress max="100" value={job.progress||0}/><p>Az állapot a szerveren megmarad. Ha bezárod vagy újratöltöd az oldalt, a folyamat innen folytatható.</p></section>}{error&&<p className="auth-error" role="alert">{error}</p>}</section><GarminConnectionCard onStatus={onGarminStatus}/></>}
