import { BookOpen, Target, TrendingUp } from "lucide-react";
import { MetricHelp } from "../components/Explainability.jsx";
import { PageHeader } from "../components/PageHeader.jsx";
import { useDashboardData } from "../lib/api.js";

const LEVELS=["építkező","átlagos","jó","kiváló","elit"];
const cardHelp={
  vo2max:["VO2max"],
  aerobic:["Heti aerob mozgás","Az elmúlt lezárt hetek átlagos mérsékelt és intenzív perce a Garmin szerint. A magyar lakossági felmérés a munkán kívüli aerob sporttal töltött heti időt méri; a WHO hetente legalább 150 perc mérsékelt (vagy 75 perc intenzív) mozgást ajánl."],
  strength:["Rendszeres erősítés","Az elmúlt 4 hét erőedzéseinek heti átlaga. A WHO hetente legalább 2 nap izomerősítő mozgást ajánl; a magyar felnőttek kisebbsége teljesíti."],
  rhr:["Nyugalmi pulzus"],
  sleep:["Alvás"],
  steps:["Napi lépésszám"],
  fitness_age:["Fittségi kor"],
};

function PercentileBar({card}){if(card.percentile==null)return <div className="level-scale" aria-label={`Szint: ${card.category}`}>{LEVELS.map((name,index)=><i key={name} className={index<=card.level?"on":""} title={name}/>)}</div>;const value=Math.max(2,Math.min(100,card.percentile));return <div className="percentile-bar"><div className="percentile-track"><i style={{width:`${value}%`}}/><b style={{left:`${value}%`}}/></div><div className="percentile-scale"><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div><MetricHelp term="Percentilis"><span className="percentile-label">{card.atLeast?`legalább ${card.percentile}. percentilis`:`≈ ${card.percentile}. percentilis`}{card.cohort?` · ${card.cohort}`:""}</span></MetricHelp></div>}

function BenchmarkCard({card,sourceIndex}){const [term,text]=cardHelp[card.key]||[card.title];const missing=card.status!=="ok";return <article className={`card benchmark-card ${missing?"missing":""}`}><div className="benchmark-card-head"><MetricHelp term={term} text={text}><span className="benchmark-title">{card.title}</span></MetricHelp>{!missing&&card.category&&<MetricHelp term="Szint"><span className={`level-chip level-${card.level}`}>{card.category}</span></MetricHelp>}</div>{missing?<p className="benchmark-missing">{card.headline}</p>:<><strong className="benchmark-value">{card.valueText}</strong><PercentileBar card={card}/><p className="benchmark-headline">{card.headline}</p>{card.detail&&<p className="benchmark-detail">{card.detail}</p>}{card.trend&&<p className="benchmark-line"><TrendingUp size={16}/><span>{card.trend}</span></p>}{card.nextGoal&&<p className="benchmark-line goal"><Target size={16}/><span>{card.nextGoal}</span></p>}</>}<div className="benchmark-card-foot">{card.confidence&&<span className={`confidence ${card.confidence==="tájékoztató"?"soft":""}`}>{card.confidence==="tájékoztató"?"TÁJÉKOZTATÓ":`${card.confidence.toUpperCase()} MEGBÍZHATÓSÁG`}</span>}<span className="benchmark-sources">Forrás: {card.sources.map(key=><a key={key} href={`#forras-${key}`}>[{sourceIndex[key]}]</a>)}</span>{card.caveat&&<small>{card.caveat}</small>}</div></article>}

export function BenchmarksPage(){const data=useDashboardData(),benchmarks=data?.benchmarks;if(!data)return <><PageHeader eyebrow="ÖSSZEVETÉS" title="Hol tartasz?"/><p className="sync-gate-loading">Adatok betöltése…</p></>;if(!benchmarks)return <><PageHeader eyebrow="ÖSSZEVETÉS" title="Hol tartasz?"/><section className="card benchmark-intro"><p>Az összevetéshez a Garmin-sportprofilod kell (nem, életkor, VO2max). Indíts egy új szinkront a „Ma” oldalon.</p></section></>;const sourceIndex=Object.fromEntries(benchmarks.sources.map((source,index)=>[source.key,index+1])),profile=benchmarks.profile||{},who=profile.sex&&profile.age?`${profile.age} éves ${profile.sex==="male"?"férfi":"nő"}`:"ismeretlen nem és kor";return <><PageHeader eyebrow="ÖSSZEVETÉS" title="Hol tartasz?"/><section className="card benchmark-intro"><div><b>Kivel hasonlítunk?</b><p>A Garmin-profilod alapján: {who}. Minden mutatót a saját nemed és korcsoportod forrásolt referenciaértékeihez mérünk; ahol nincs ilyen, ott a hivatalos ajánlásokhoz.{benchmarks.demo?" Most bemutató adatokat látsz.":""}</p></div><p className="benchmark-disclaimer">Sportteljesítményi összevetés, nem orvosi értékelés.</p></section><div className="benchmark-grid">{benchmarks.cards.map(card=><BenchmarkCard key={card.key} card={card} sourceIndex={sourceIndex}/>)}</div><section className="card benchmark-source-list"><span className="eyebrow"><BookOpen size={15}/> FORRÁSOK</span><ol>{benchmarks.sources.map(source=><li key={source.key} id={`forras-${source.key}`}><b>{source.label}</b><span>{source.citation}</span><span><a href={source.url} target="_blank" rel="noopener noreferrer">{source.url.replace(/^https?:\/\//,"")}</a> · {source.license}</span></li>)}</ol></section></>}
