import { useState } from "react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { DecisionTranslation } from "../components/DecisionTranslation.jsx";
import { PageHeader } from "../components/PageHeader.jsx";
import { useDashboardState } from "../lib/api.js";
import { budapestToday } from "../lib/overviewData.js";
import { buildTrainingInterpretation, summarizeTrainingPeriods } from "../lib/periods.js";

const RANGES=[["30 nap",30],["60 nap",60],["90 nap",90],["1 év",365]];
const COLORS=["#23766b","var(--accent)","#3b82f6","#f59e0b","#ef4444"];

export function LiveTrendsPage({profile}){const {status,data}=useDashboardState(),[range,setRange]=useState("90 nap"),days=RANGES.find(([label])=>label===range)[1],today=budapestToday();
  const rawPoints=(data?.trends||[]).slice(-Math.max(2,Math.ceil(days/7))),points=rawPoints.map(x=>({...x,week:new Date(`${x.date}T12:00:00`).toLocaleDateString("hu-HU",{month:"short",day:"numeric"})})),current=rawPoints.at(-1),previous=rawPoints.at(-2)||current,delta=key=>current&&previous?Math.round((Number(current[key]||0)-Number(previous[key]||0))*10)/10:null;
  const from=new Date(`${today}T12:00:00`);from.setDate(from.getDate()-days+1);const fromIso=from.toISOString().slice(0,10),periodSessions=(data?.sessions||[]).filter(item=>item.date>=fromIso&&item.date<=today),weeklyFrequency=Math.round(periodSessions.length/(days/7)*10)/10;
  let feedback={};try{feedback=JSON.parse(localStorage.getItem("hybrid-activity-feedback")||"{}")}catch{}
  const rpes=periodSessions.map(item=>feedback[item.id]?.rpe).filter(Boolean),averageRpe=rpes.length?Math.round(rpes.reduce((sum,value)=>sum+value,0)/rpes.length*10)/10:null,zoneValues=Array.isArray(data?.zones)?data.zones:null,total=zoneValues?zoneValues.reduce((a,b)=>a+b,0):0,eventDays=profile.eventDate?Math.ceil((new Date(profile.eventDate)-new Date())/86400000):null;
  const summaries=[[current?Math.round(current.ctl||0):"—","CTL",delta("ctl")],[current?Number(current.atl||0).toFixed(0):"—","ATL",delta("atl")],[current?Number(current.tsb||0).toFixed(1):"—","TSB",delta("tsb")],[status==="ready"?weeklyFrequency:"—","EDZÉS / HÉT",null],[averageRpe??"—","ÁTLAG RPE",null]];
  const comparison=summarizeTrainingPeriods(data?.sessions,days,today),interpretation=buildTrainingInterpretation(comparison,profile);
  return <><PageHeader eyebrow="SZEMÉLYES FEJLŐDÉSTÖRTÉNET" title="Terhelés és forma"><div className="segmented" role="group" aria-label="Vizsgált időszak">{RANGES.map(([label])=><button key={label} aria-pressed={range===label} className={range===label?"active":""} onClick={()=>setRange(label)}>{label}</button>)}</div></PageHeader>
    {status!=="ready"&&<p className="trend-state" role={status==="error"?"alert":"status"}>{status==="loading"?"A trendadatok betöltése…":status==="error"?"Az adatok betöltése nem sikerült. Nem jelenítünk meg helyettük mintagrafikont.":"Még nincs szinkronizált Garmin-adat. A szinkronizálást az Áttekintés vagy a Ma oldalon indíthatod."}</p>}
    <DecisionTranslation eyebrow="IDŐSZAK-ÖSSZEHASONLÍTÁS" title="Mit mond az időszak a fejlődésedről?" period={`${comparison.currentLabel} · összevetve: ${comparison.previousLabel}`} items={interpretation.items} note={interpretation.note} state={status}/>
    <section className="trend-summary">{summaries.map(([value,label,change])=><div className="card" key={label}><strong>{value}</strong><span>{label}</span>{change!==null&&<small className={change>=0?"up":"down"}>{change>=0?"+":""}{change} az előző héthez képest</small>}</div>)}</section>
    <section className="card chart-card"><div className="section-head"><span className="eyebrow">HOSSZÚ TÁVÚ TERHELÉS · ATL · CTL · TSB</span><small>HYBRID ATHLETE-BECSLÉS · {range.toUpperCase()}</small></div>{points.length?<ResponsiveContainer width="100%" height={320}><LineChart data={points} margin={{top:8,right:18,bottom:28,left:34}}><CartesianGrid stroke="#2a2b2b" vertical={false}/><XAxis dataKey="week" stroke="#8b8e8d" fontSize={10} label={{value:"Időszak (hét)",position:"insideBottom",offset:-18,fill:"#aeb2b0"}}/><YAxis stroke="#8b8e8d" fontSize={10} label={{value:"Terhelési pont",angle:-90,position:"insideLeft",offset:-22,fill:"#aeb2b0"}}/><Tooltip contentStyle={{background:"#181a19",border:"1px solid #343635"}} formatter={(value,name)=>[`${value} pont`,name]} labelFormatter={label=>`Időszak: ${label}`}/><Line type="monotone" dataKey="ctl" name="Krónikus terhelés" stroke="var(--accent)" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="atl" name="Akut terhelés" stroke="#f59e0b" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="tsb" name="Forma (TSB)" stroke="#3b82f6" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer>:<p className="overview-empty">{status==="loading"?"A grafikon betöltése…":"Erre az időszakra nincs megjeleníthető trendadat. Nem helyettesítjük mintagrafikonnal."}</p>}<p className="chart-axis-note">X tengely: időszak hetekben · Y tengely: súlyozott terhelési pont. A CTL a hosszabb távú edzettséget, az ATL a rövid távú fáradtságot, a TSB pedig a kettő különbségéből becsült formát mutatja.</p></section>
    <div className="trend-bottom"><section className="card zone-card"><div className="section-head"><span className="eyebrow">ZÓNAIDŐ ELOSZLÁS · AKTUÁLIS HÉT</span><small>{zoneValues?`${total} PERC`:"NINCS ADAT"}</small></div>{zoneValues?zoneValues.map((minutes,index)=><div className="zone-row" key={index}><b>Z{index+1}</b><span><i style={{width:`${total?minutes/total*100:0}%`,background:COLORS[index]}}/></span><strong>{minutes}p</strong></div>):<p className="decision-translation-state">A heti pulzuszóna-adat még nem érhető el.</p>}</section><section className="card dimensions"><div className="section-head"><span className="eyebrow">SZEMÉLYES FÓKUSZ</span><small>{profile.goal.toUpperCase()}</small></div><div className="goal-progress"><strong>{profile.strengthRatio}%</strong><span>ERŐ CÉL</span><i><b style={{width:`${profile.strengthRatio}%`}}/></i></div><div className="goal-progress"><strong>{profile.weeklyHours}ó</strong><span>HETI IDŐKERET</span><i><b style={{width:`${Math.min(100,profile.weeklyHours/15*100)}%`}}/></i></div>{profile.eventName&&<div className="event-focus"><span className="eyebrow">KÖVETKEZŐ ESEMÉNY</span><h2>{profile.eventName}</h2><p>{eventDays!==null&&eventDays>=0?`${eventDays} nap van hátra.`:"Az esemény dátuma elmúlt."} A trendeket a {profile.goal.toLowerCase()} célod szerint értelmezzük.</p></div>}</section></div></>}
