import { useState } from "react";
import { Activity, ChevronLeft, ChevronRight, Pencil, Plus } from "lucide-react";
import { PageHeader } from "../components/PageHeader.jsx";
import { BatchMoveEditor } from "../components/calendar/BatchMoveEditor.jsx";
import { PlanEditor } from "../components/calendar/PlanEditor.jsx";
import { WeeklyTemplateEditor } from "../components/calendar/WeeklyTemplateEditor.jsx";
import { useDashboardData } from "../lib/api.js";
import { dayCodes, isoDate } from "../lib/dates.js";
import { buildPersonalWeek, emptyPlan, evaluatePlan } from "../lib/planning.js";

export function PersistentCalendarPage({profile,cloudState,onCloudPatch}){
  const data=useDashboardData(),activities=data?.sessions||[],today=data?.today||isoDate(new Date()),anchor=new Date(`${today}T12:00:00`),[month,setMonth]=useState(()=>new Date(anchor.getFullYear(),anchor.getMonth(),1)),[selected,setSelected]=useState(()=>isoDate(anchor)),[editor,setEditor]=useState(null),[templateEditor,setTemplateEditor]=useState(false),[batchEditor,setBatchEditor]=useState(false),plans=cloudState?.plans||[],planned=new Map(plans.map(item=>[item.date,item])),actual=new Map(activities.map(item=>[item.date,{...item,title:item.name,duration:item.durationMin,status:"done"}]));
  const first=new Date(month.getFullYear(),month.getMonth(),1),gridStart=new Date(first);gridStart.setDate(first.getDate()-((first.getDay()+6)%7));
  const cells=Array.from({length:42},(_,index)=>{const date=new Date(gridStart);date.setDate(gridStart.getDate()+index);const key=isoDate(date),item=actual.get(key)||planned.get(key);return {date,key,item,current:date.getMonth()===month.getMonth()}}),selectedPlan=planned.get(selected),selectedActual=actual.get(selected),selectedItem=selectedActual||selectedPlan,comparison=selectedPlan?evaluatePlan(selectedPlan,activities,today):null,selectedDate=new Date(`${selected}T12:00:00`),monthLabel=month.toLocaleDateString("hu-HU",{year:"numeric",month:"long"}),shift=value=>setMonth(current=>new Date(current.getFullYear(),current.getMonth()+value,1)),save=plan=>{onCloudPatch({plan});setSelected(plan.date);setEditor(null)},remove=id=>{onCloudPatch({deletePlan:id});setEditor(null)},template=buildPersonalWeek(profile,data),saveTemplate=items=>{onCloudPatch({plans:items});setTemplateEditor(false);if(items[0])setSelected(items[0].date)},saveBatch=items=>{onCloudPatch({plans:items});setBatchEditor(false);if(items[0])setSelected(items[0].date)};
  return <><PageHeader eyebrow="SZEMÉLYES HETI TERV" title="Terv és tény"><div className="calendar-actions"><button aria-label="Előző hónap" onClick={()=>shift(-1)}><ChevronLeft size={14}/></button><b>{monthLabel}</b><button aria-label="Következő hónap" onClick={()=>shift(1)}><ChevronRight size={14}/></button><button className="calendar-new" onClick={()=>setEditor(emptyPlan(selected))}><Plus size={15}/> ÚJ EDZÉS</button></div></PageHeader><div className="calendar-toolbar"><div className="calendar-legend"><span><i className="planned"/>TERVEZETT</span><span><i className="done"/>TELJESÍTETT</span><span><i className="extra"/>GARMIN ELŐZMÉNY</span></div><div className="calendar-toolbar-actions"><button disabled={plans.length<2} onClick={()=>setBatchEditor(true)}>TÖBB EDZÉS MOZGATÁSA</button><button onClick={()=>setTemplateEditor(true)}>HETI SABLON SZEMÉLYRE SZABÁSA</button></div></div><section className="calendar card"><div className="weekdays">{["HÉTFŐ","KEDD","SZERDA","CSÜTÖRTÖK","PÉNTEK","SZOMBAT","VASÁRNAP"].map(day=><b key={day}>{day}</b>)}</div><div className="calendar-grid">{cells.map(cell=><button key={cell.key} className={`${cell.key===selected?"selected":""} ${!cell.current?"outside":""}`} onClick={()=>setSelected(cell.key)}><span>{cell.date.getDate()}</span>{cell.item&&<div className={cell.item.status}><Activity size={13}/><b>{cell.item.type}</b><small>{cell.item.title} · {cell.item.duration}p</small></div>}</button>)}</div></section><div className="calendar-detail card"><div><span className="eyebrow">KIVÁLASZTOTT NAP</span><h2>{selectedDate.toLocaleDateString("hu-HU",{month:"long",day:"numeric"})}</h2></div><div><p>{selectedItem?`${selectedItem.title} · ${selectedItem.duration} perc · ${selectedActual?"Garmin-adat":"személyes terv"}`:selectedDate.getDay()===0||dayCodes[selectedDate.getDay()]===profile.restDay?"Tervezett pihenőnap.":"Nincs edzés erre a napra."}</p>{comparison&&<div className={`plan-comparison ${comparison.status.replaceAll(" ","-")}`}><b>{comparison.status.toUpperCase()}</b>{comparison.activity&&<span>{comparison.method} párosítás · tény {comparison.activity.durationMin} perc · eltérés {comparison.difference>0?"+":""}{comparison.difference} perc</span>}</div>}</div><div className="calendar-detail-actions">{selectedPlan&&<button onClick={()=>setEditor(selectedPlan)}><Pencil size={14}/> SZERKESZTÉS ÉS PÁROSÍTÁS</button>}<button className="primary" onClick={()=>setEditor(emptyPlan(selected))}><Plus size={14}/> EDZÉS HOZZÁADÁSA</button></div></div>{editor&&<PlanEditor value={editor} activities={activities} onSave={save} onDelete={remove} onClose={()=>setEditor(null)}/>} {templateEditor&&<WeeklyTemplateEditor items={template} onSave={saveTemplate} onClose={()=>setTemplateEditor(false)}/>} {batchEditor&&<BatchMoveEditor plans={plans} onSave={saveBatch} onClose={()=>setBatchEditor(false)}/>}</>}
