import { useEffect, useState } from "react";
import { RefreshCw, X } from "lucide-react";
import { AnimatedBrandMark } from "../components/Brand.jsx";
import { CheckIn } from "../components/CheckIn.jsx";
import { CoachingTips } from "../components/CoachingTips.jsx";
import { Decision } from "../components/Decision.jsx";
import { Heatmap } from "../components/Heatmap.jsx";
import { MetricList } from "../components/ReadinessMetrics.jsx";
import { budapestToday } from "../lib/overviewData.js";
import { personalizeDashboard } from "../lib/personalize.js";
import { useGarminSync } from "../lib/useGarminSync.js";

export function TodayLive({profile,cloudState,onCloudPatch,onDataChanged}){
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(""),[whyOpen,setWhyOpen]=useState(false),[checkin,setCheckin]=useState(null);
  const load=()=>fetch("/api/dashboard").then(async r=>{const text=await r.text();let body=null;try{body=JSON.parse(text)}catch{throw new Error("A helyi Garmin API nem érhető el; a beépített mintaadatok láthatók.")}if(!r.ok)throw new Error(body?.error||"Az adatok nem tölthetők be.");return body}).then(value=>{setData(value);setLoadError("")}).catch(e=>setLoadError(e.message||"Az adatok nem tölthetők be.")).finally(()=>setLoading(false));
  useEffect(()=>{load()},[]);
  const {syncing,job:syncJob,error:syncError,start:syncNow,resumeRunId}=useGarminSync({onCompleted:async()=>{await load();onDataChanged?.()}}),error=syncError||loadError;
  const checkinKey=budapestToday();useEffect(()=>{const cloud=cloudState?.checkins?.[checkinKey];if(cloud){setCheckin(cloud);localStorage.setItem(`hybrid-checkin-${checkinKey}`,JSON.stringify(cloud));return}try{setCheckin(JSON.parse(localStorage.getItem(`hybrid-checkin-${checkinKey}`)||"null"))}catch{setCheckin(null)}},[checkinKey,cloudState]);
  const saveCheckin=value=>{localStorage.setItem(`hybrid-checkin-${checkinKey}`,JSON.stringify(value));setCheckin(value);onCloudPatch({checkin:{date:checkinKey,value}})},stamp=data?.generatedAt?new Date(data.generatedAt).toLocaleTimeString("hu-HU",{hour:"2-digit",minute:"2-digit"}):"—",view=personalizeDashboard(data,profile,checkin),week=view.week,formatMinutes=value=>`${Math.floor(value/60)}ó ${value%60}p`;
  const dayLabel=new Date(`${checkinKey}T12:00:00`).toLocaleDateString("hu-HU",{year:"numeric",month:"long",day:"numeric",weekday:"long"}),
    header=title=><header><div><span className="eyebrow">{dayLabel}</span><h1>{title}</h1></div><div className="header-actions"><span>{error?error:data?`${data.source==="garmin"?"GARMIN":"DEMO"} · ${stamp}`:""}</span><button onClick={()=>syncNow(resumeRunId)} disabled={syncing}>{syncing?<AnimatedBrandMark className="sync-brand-mark"/>:<RefreshCw size={14}/>} {syncing?`${Math.round(syncJob?.progress||0)}%`:resumeRunId?"SZINKRON FOLYTATÁSA":"SZINKRON"}</button></div></header>,
    progress=syncing&&syncJob&&<section className="sync-progress" role="status" aria-live="polite"><div><AnimatedBrandMark/><span><b>Teljes Garmin-előzmény szinkronizálása</b><small>{syncJob.message}</small></span><strong>{Math.round(syncJob.progress||0)}%</strong></div><progress max="100" value={syncJob.progress||0}/><p>Az állapot a Neon adattárban megmarad. Ha bezárod vagy újratöltöd az oldalt, a folyamat innen folytatható.</p></section>,
    readinessValid=typeof data?.readiness==="number"&&Number.isFinite(data.readiness)&&data.readiness>=0&&data.readiness<=100;
  // The recommendation needs today's self-report first, and is never built on an earlier day's score.
  if(!checkin?.savedAt)return <>{header("Kezdjük a napi állapotfelméréssel")}{progress}<main className="checkin-gate"><div><span className="eyebrow">A MAI AJÁNLÁS ELSŐ LÉPÉSE</span><h2>Hogyan érzed magad ma?</h2><p>A válaszaidat összevetjük a Garminból érkező regenerációs és terhelési adatokkal. Az ajánlás csak ezután jelenik meg.</p></div><CheckIn value={checkin} onSave={saveCheckin} required/></main></>;
  if(loading||!data||data.today!==checkinKey||!readinessValid)return <>{header("A mai döntés")}{progress}<main className="today-unavailable"><section className="card" role={error?"alert":"status"}><h2>{loading?"A Garmin-adatok betöltése…":"A mai ajánláshoz még nincs megfelelő adat"}</h2><p>{loading?"Az állapotfelmérésed már rendelkezésre áll. Várjuk a hozzá tartozó Garmin-adatokat.":error||(data&&data.today!==checkinKey?`Az utolsó Garmin-összesítés ${new Date(`${data.today}T12:00:00`).toLocaleDateString("hu-HU",{month:"long",day:"numeric"})}-i. Indíts szinkronizálást; a korábbi pontszámot nem tekintjük mai terhelhetőségnek.`:"A mai terhelhetőségi pontszám hiányzik vagy érvénytelen. Nem helyettesítjük becsült mintaértékkel.")}</p>{!loading&&<button onClick={()=>{setLoading(true);load()}}>Adatok újratöltése</button>}</section><CheckIn value={checkin} onSave={saveCheckin}/></main></>;
  return <>{header("A mai döntés")}{progress}<main className="dashboard"><div className="left"><Decision data={data} profile={profile} checkin={checkin} onWhy={()=>setWhyOpen(true)}/><CheckIn value={checkin} onSave={saveCheckin}/><MetricList data={data}/></div><div className="right"><section className="card load-card"><div className="section-head"><span className="eyebrow">TERHELÉS · 12 HÉT</span><small>{data?.source==="garmin"?"GARMIN ADAT":"DEMO ADAT"}</small></div><Heatmap values={data?.heat}/><div className="heat-legend"><span>KEVESEBB</span><i data-level="1"/><i data-level="2"/><i data-level="3"/><span>TÖBB</span></div></section><section className="card week"><div className="section-head"><span className="eyebrow">HETI KERET</span><small>{week.daysDone} / {week.daysTarget} NAP</small></div><div className="weekbar"><i style={{width:`${week.progress}%`,borderRight:week.progress<100?"42px solid #f59e0b":"0"}}/></div><div className="week-stats"><div><strong>{week.totalLoad.toLocaleString("hu-HU")}</strong><span>TERHELÉS</span></div><div><strong>{formatMinutes(week.actualMinutes)}</strong><span>{formatMinutes(week.targetMinutes)} CÉLBÓL</span></div><div><strong>{week.actualStrength}%</strong><span>{week.targetStrength}% ERŐ CÉL</span></div></div><p>A heti időkeret {week.progress}%-a teljesült. A mai ajánlás a {profile.goal.toLowerCase()} célodhoz igazodik.</p></section><CoachingTips tips={data?.coaching?.tips||[]} insights={view.insights}/></div></main>{whyOpen&&<div className="modal-backdrop" onClick={()=>setWhyOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setWhyOpen(false)}><X size={18}/></button><span className="eyebrow">SZEMÉLYES AJÁNLÁS</span><h2>Miért {view.decision.title.toLowerCase()}?</h2><p>{view.decision.rationale}</p><ul><li>{data.readinessSource==="garmin_training_readiness"?"Garmin Training Readiness":"Becsült terhelhetőség"}: {data.readiness}/100</li><li>Check-in után: {view.adjustedReadiness}/100</li><li>Fő cél: {profile.goal}</li><li>Heti keret: {profile.weeklyHours} óra, {profile.strengthRatio}% erő</li><li>Edzésirány: {profile.preference}</li></ul><button className="primary" onClick={()=>setWhyOpen(false)}>Értem</button></div></div>}</>;
}
