import { useEffect, useState } from "react";

// Dashboard snapshot with an explicit state: "loading" | "ready" | "empty" (no sync yet) | "error".
// Reloads when a sync finishes ("hybrid-dashboard-refresh"); never substitutes sample data.
export function useDashboardState(){const [state,setState]=useState({status:"loading",data:null});useEffect(()=>{let active=true;const load=async()=>{try{const response=await fetch("/api/dashboard",{cache:"no-store"}),value=await response.json().catch(()=>null);if(!active)return;if(response.status===404&&value?.code==="no_dashboard_data")setState({status:"empty",data:null});else if(!response.ok||!value||typeof value!=="object"||Array.isArray(value))setState({status:"error",data:null});else setState({status:"ready",data:value})}catch{if(active)setState({status:"error",data:null})}};load();window.addEventListener("hybrid-dashboard-refresh",load);return()=>{active=false;window.removeEventListener("hybrid-dashboard-refresh",load)}},[]);return state}
export function useDashboardData(){return useDashboardState().data}
export async function fetchCloudState(){const response=await fetch("/api/state");if(!response.ok)throw new Error("cloud-state-unavailable");return response.json()}
export async function patchCloudState(patch){const response=await fetch("/api/state",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});if(!response.ok)throw new Error("cloud-state-save-failed");return response.json()}
export function mergeCloudState(current,patch){const next={...(current||{}),...patch};if(patch.checkin)next.checkins={...(current?.checkins||{}),[patch.checkin.date]:patch.checkin.value};if(patch.feedback)next.feedback={...(current?.feedback||{}),[patch.feedback.activityId]:patch.feedback.value};if(patch.plan)next.plans=[...(current?.plans||[]).filter(item=>item.id!==patch.plan.id),patch.plan];if(patch.plans){const replaceDates=new Set(patch.replacePlanDates||[]),plans=new Map((current?.plans||[]).filter(item=>!replaceDates.has(item.date)).map(item=>[item.id,item]));patch.plans.forEach(item=>plans.set(item.id,item));next.plans=[...plans.values()]}if(patch.deletePlan)next.plans=(current?.plans||[]).filter(item=>item.id!==patch.deletePlan);delete next.checkin;delete next.feedback;delete next.plan;delete next.deletePlan;delete next.replacePlanDates;return next}
export async function authRequest(payload){const response=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"A fiókművelet sikertelen.");return body}
export function clearLocalPersonalData(){try{Object.keys(localStorage).filter(key=>key.startsWith("hybrid-")).forEach(key=>localStorage.removeItem(key))}catch{}try{sessionStorage.clear()}catch{}}
