export const metricGlossary={
  "Readiness":"A 0–100-as terhelhetőségi pontszám azt becsüli, mennyire áll készen a szervezeted a mai edzésre. A magasabb érték általában több terhelést enged, az alacsonyabb érték regenerációt vagy könnyítést indokol.",
  "Bizonyosság":"Azt mutatja, mennyire teljesek és következetesek az értékeléshez használt adatok. Alacsony bizonyosságnál az ajánlást óvatosabban érdemes kezelni.",
  "HRV (éjszakai)":"A szívverések közötti idő apró változékonysága alvás közben. A saját megszokott értékedhez képest tartós csökkenés fáradtságot vagy stresszt jelezhet; egyetlen nap önmagában nem döntő.",
  "Alvás":"Az alvás hossza és minősége a regeneráció egyik fő jele. Kevés vagy rossz alvás ronthatja a teljesítményt, a koordinációt és a terheléstűrést.",
  "Nyugalmi pulzus":"A nyugalomban mért szívverésszám. A saját alapértékedhez képest szokatlan emelkedés fáradtságot, stresszt vagy kezdődő betegséget jelezhet.",
  "TSB":"A rövid és hosszú távú terhelés különbségéből becsült frissesség. Pozitív érték inkább friss állapotot, erősen negatív érték felhalmozott fáradtságot jelez.",
  "CTL":"A nagyjából hathetes terhelésből számolt hosszú távú edzettségi szint. Lassan változik; emelkedése tartós munkát, túl gyors növekedése fokozott kockázatot jelenthet.",
  "ATL":"Az utóbbi körülbelül egy hét terhelését összegző akut fáradtság. Gyorsan emelkedik egy nehéz blokk után, és pihenéssel gyorsabban csökken, mint a CTL.",
  "CTL · ATL · TSB":"CTL: hosszú távú edzettség. ATL: rövid távú fáradtság. TSB: a kettő különbségéből becsült frissesség. Együtt azt mutatják, hogy fejlődik-e a formád, és közben mennyi fáradtságot halmoztál fel.",
  "Terhelés":"Az edzés időtartamát és intenzitását egy közös pontszámba sűríti. Magasabb szám nagyobb regenerációs igényt jelent; elsősorban a saját korábbi értékeidhez hasonlítsd.",
  "Edzésidő":"Az adott időszakban edzéssel töltött percek összege. A célhoz viszonyítva megmutatja, hogy a heti terv mennyire reális és teljesíthető.",
  "Erő arány":"Megmutatja, a heti edzésidő mekkora része volt erőedzés. A célértéktől való eltérés segít a következő edzéstípus kiválasztásában.",
  "RPE":"Az edzés szubjektív nehézsége 1–10-ig. Az 1 nagyon könnyű, a 10 maximális; a tartósan magas RPE több regenerációt vagy kisebb terhelést indokolhat.",
  "Pulzus":"Az átlagos percenkénti szívverés. A megszokottnál magasabb pulzus azonos tempónál fáradtságra, melegre, folyadékhiányra vagy stresszre utalhat.",
  "Pulzuszóna":"Az intenzitás pulzus alapján meghatározott tartománya. Z1–Z2 könnyű, aerob munka; Z3 közepes; Z4–Z5 nagy intenzitás, ezért több regenerációt igényel.",
  "Táv":"Az edzés során megtett távolság. Önmagában nem mutatja a nehézséget: a tempóval, szintemelkedéssel és pulzussal együtt értelmezendő.",
  "Edzésgyakoriság":"Az egy hétre jutó edzések átlagos száma. A következetességet jelzi, de a több alkalom nem feltétlenül jobb, ha a regeneráció nem elég.",
  "Felkészültség":"A célodhoz szükséges következetesség, terhelés, egyensúly, regeneráció és célspecifikusság 0–100-as összesítése. Az alacsonyabb részpontszámok jelölik a fejlesztendő területeket.",
  "Időkeret":"A vállalt heti edzésidő teljesülési aránya. A tartós elmaradás túl feszes tervet, a tartós túllépés túlzott terhelést jelezhet.",
};
