import { dayCodes, isoDate } from "./dates.js";
import { personalizeDashboard } from "./personalize.js";
import { buildWeeklyClosure } from "./planOutcomes.js";

export function buildPersonalWeek(profile,data){
  const anchor=new Date(`${data?.today||isoDate(new Date())}T12:00:00`),monday=new Date(anchor);monday.setDate(anchor.getDate()-((anchor.getDay()+6)%7));
  const available=Array.from({length:7},(_,index)=>{const date=new Date(monday);date.setDate(monday.getDate()+index);return {date,code:dayCodes[date.getDay()]}}).filter(day=>profile.trainingDays.includes(day.code)&&day.code!==profile.restDay);
  const total=Math.max(60,Number(profile.weeklyHours||8)*60),count=Math.max(1,available.length),strengthCount=Math.min(count,Math.round(count*Number(profile.strengthRatio||0)/100));
  const strengthSlots=new Set(Array.from({length:strengthCount},(_,i)=>Math.min(count-1,Math.round((i+.5)*count/Math.max(1,strengthCount)-.5))));
  const base=Math.floor(total/count/5)*5,remainder=total-base*count;
  return available.map((day,index)=>{const strength=strengthSlots.has(index),duration=base+(index===count-1?remainder:0),quality=index===Math.floor(count/2)&&!strength;
    const cardioTitle=profile.goal==="Hegyi állóképesség"?(quality?"Emelkedős tempó":"Hegyi alapállóképesség"):profile.goal==="Futóteljesítmény"?(quality?"Tempófutás":"Zone 2 futás"):profile.goal==="Általános egészség"?"Könnyű aerob edzés":quality?"Minőségi kardió":"Zone 2 alapozás";
    return {date:isoDate(day.date),type:strength?"Erő":"Kardió",title:strength?(profile.goal==="Erőfejlesztés"&&quality?"Progresszív erőedzés":"Teljes testes erő"):cardioTitle,duration,intensity:quality?"közepes–magas":"könnyű–közepes",rpe:quality?7:5,purpose:`${profile.goal} · ${strength?"erőkomponens":"állóképességi komponens"}`,status:"planned"};
  });
}
export function buildGoalReadiness(data,profile){const sessions=data?.sessions||[],cutoff=new Date(`${data?.today||isoDate(new Date())}T12:00:00`);cutoff.setDate(cutoff.getDate()-27);const recent=sessions.filter(item=>new Date(item.date)>=cutoff),view=personalizeDashboard(data,profile),strength=recent.filter(item=>item.type==="Erő").length,cardio=recent.filter(item=>["Futás","Túrázás","Kerékpár"].includes(item.type)),longest=recent.reduce((max,item)=>Math.max(max,Number(item.durationMin||0)),0),actualStrength=recent.length?strength/recent.length*100:0,consistency=Math.min(100,recent.length/Math.max(8,(profile.trainingDays?.length||4)*4)*100),timeFit=Math.min(100,view.week.progress),balance=Math.max(0,100-Math.abs(actualStrength-profile.strengthRatio)*2),recovery=Math.min(100,Number(data?.readiness||0)),specific=profile.goal==="Erőfejlesztés"?Math.min(100,strength/8*100):profile.goal==="Hegyi állóképesség"?Math.min(100,(cardio.filter(item=>item.type==="Túrázás").length+longest/90)*25):Math.min(100,(cardio.length+longest/60)*12),components=[["Következetesség",consistency],["Heti keret",timeFit],["Erő–kardió egyensúly",balance],["Regeneráció",recovery],["Célspecifikusság",specific]],score=Math.round(components.reduce((sum,[,value])=>sum+value,0)/components.length),gaps=[];if(consistency<60)gaps.push("kevés következetesen rögzített edzés az elmúlt 28 napban");if(timeFit<70)gaps.push("a heti időkeret teljesítése elmarad a céltól");if(balance<65)gaps.push("az erő–kardió arány eltér a személyes célodtól");if(recovery<60)gaps.push("a regeneráció jelenleg korlátozza a terhelhetőséget");if(specific<60)gaps.push(`kevés ${profile.goal.toLowerCase()}-specifikus edzés`);const eventDays=profile.eventDate?Math.ceil((new Date(profile.eventDate)-new Date())/86400000):null;return {score,components:components.map(([name,value])=>({name,score:Math.round(value)})),gaps:gaps.length?gaps:["nincs kiemelt hiány a jelenlegi adatok alapján"],recentCount:recent.length,longest,eventDays}}

const periodizationFocus={"Hibrid teljesítmény":{cardio:"Zone 2 és tempó",strength:"teljes testes erő",key:"Hibrid kulcsedzés"},"Futóteljesítmény":{cardio:"Futás",strength:"futást támogató erő",key:"Minőségi futóedzés"},"Erőfejlesztés":{cardio:"Regeneráló kardió",strength:"progresszív erő",key:"Fő erőedzés"},"Hegyi állóképesség":{cardio:"Emelkedős túra/futás",strength:"alsótest és stabilitás",key:"Hosszú hegyi nap"},"Általános egészség":{cardio:"Könnyű aerob munka",strength:"teljes testes erő",key:"Kiegyensúlyozott edzés"}};
export function buildPeriodizedCycle(profile,data,weeks){
  const today=new Date(`${data?.today||isoDate(new Date())}T12:00:00`),nextMonday=new Date(today);nextMonday.setDate(today.getDate()+((8-today.getDay())%7||7));
  const eventDate=profile.eventDate?new Date(`${profile.eventDate}T12:00:00`):null,endMonday=eventDate&&eventDate>today?new Date(eventDate):null;if(endMonday)endMonday.setDate(eventDate.getDate()-((eventDate.getDay()+6)%7));
  const eventStart=endMonday?new Date(endMonday):null;if(eventStart)eventStart.setDate(endMonday.getDate()-(weeks-1)*7);
  const start=eventStart&&eventStart>=nextMonday?eventStart:nextMonday,available=Array.from({length:7},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return {offset:index,code:dayCodes[date.getDay()]}}).filter(day=>profile.trainingDays.includes(day.code)&&day.code!==profile.restDay),focus=periodizationFocus[profile.goal]||periodizationFocus["Hibrid teljesítmény"],totalMinutes=Number(profile.weeklyHours||8)*60;
  return Array.from({length:weeks},(_,weekIndex)=>{
    const progress=(weekIndex+1)/weeks,last=weekIndex===weeks-1,deload=!last&&(weekIndex+1)%4===0,phase=last&&profile.eventDate?"Eseményhét":last?"Levezetés":deload?"Tehermentesítés":progress<=.35?"Alapozás":progress<=.75?"Építés":"Csúcsforma",volume=last?55:deload?72:phase==="Alapozás"?82+weekIndex*3:phase==="Építés"?94+Math.min(10,weekIndex*2):90,weekMinutes=Math.round(totalMinutes*volume/100/5)*5,count=Math.max(1,available.length),strengthCount=Math.round(count*Number(profile.strengthRatio||0)/100),weekStart=new Date(start);
    weekStart.setDate(start.getDate()+weekIndex*7);
    const sessions=available.map((day,index)=>{const date=new Date(weekStart);date.setDate(weekStart.getDate()+day.offset);const strength=index<strengthCount,key=index===count-1&&!strength,duration=Math.max(20,Math.round((weekMinutes/count)*(key?1.25:strength?1:.85)/5)*5),intensity=last?"könnyű":deload?"könnyű–közepes":key&&phase!=="Alapozás"?"közepes–magas":"közepes",rpe=last?4:deload?5:key?7:6,title=strength?`${focus.strength} · ${phase}`:key?`${focus.key} · ${phase}`:`${focus.cardio} · ${phase}`;return {id:`period-${isoDate(date)}`,date:isoDate(date),type:strength?"Erő":"Kardió",title,duration,intensity,rpe,purpose:`${profile.goal} · ${phase.toLowerCase()} fázis`,note:`A ${weeks} hetes ciklus ${weekIndex+1}. hete · ${volume}% heti volumen`,status:"planned"}});
    return {index:weekIndex+1,phase,volume,weekStart:isoDate(weekStart),minutes:sessions.reduce((sum,item)=>sum+item.duration,0),focus:last&&profile.eventName?profile.eventName:focus.key,sessions};
  });
}

// Next week's proposal from the latest weekly closure, readiness and check-in. Without a plan or
// enough RPE feedback it never raises the load; missing readiness is unknown, not an assumed 70.
export function buildAdaptiveWeek(profile,data,cloudState){const todayValue=data?.today||isoDate(new Date()),today=new Date(`${todayValue}T12:00:00`),nextMonday=new Date(today);nextMonday.setDate(today.getDate()+((8-today.getDay())%7||7));const nextEnd=new Date(nextMonday);nextEnd.setDate(nextMonday.getDate()+6);const plans=cloudState?.plans||[],nextPlans=plans.filter(item=>item.date>=isoDate(nextMonday)&&item.date<=isoDate(nextEnd)),base=nextPlans.length?nextPlans:buildPeriodizedCycle(profile,data,4)[0].sessions.map((item,index)=>{const dayOffset=(new Date(`${item.date}T12:00:00`).getDay()+6)%7,date=new Date(nextMonday);date.setDate(nextMonday.getDate()+dayOffset);return {...item,id:`adaptive-${isoDate(date)}-${index}`,date:isoDate(date)}}),activities=data?.sessions||[],feedback=cloudState?.feedback||{},closure=buildWeeklyClosure(plans,activities,feedback,todayValue),missed=closure?.missed||0,adherence=closure?.adherence??null,checkinEntries=Object.entries(cloudState?.checkins||{}).filter(([date])=>date<=todayValue).sort(([a],[b])=>b.localeCompare(a)),checkin=checkinEntries[0]?.[1],readiness=data?.readiness!=null&&Number.isFinite(Number(data.readiness))?Number(data.readiness):null,reasons=[];let adjustment=0;
  if(checkin?.illness){adjustment-=35;reasons.push("A legutóbbi check-in betegségérzetet jelez, ezért csak regeneráló terhelés marad.")}else if(checkin?.pain){adjustment-=30;reasons.push("A jelzett fájdalom miatt a következő hét intenzitása és volumene is csökken.")}
  if(readiness!==null&&readiness<55){adjustment-=20;reasons.push(`A terhelhetőségi érték ${readiness}/100, ezért most a regeneráció élvez elsőbbséget.`)}else if(readiness!==null&&readiness<70){adjustment-=10;reasons.push(`A terhelhetőségi érték ${readiness}/100, ezért kisebb edzésmennyiség javasolt.`)}
  if(Number(checkin?.fatigue||0)>=4||Number(checkin?.stress||0)>=4){adjustment-=10;reasons.push("A magas fáradtság vagy stressz indokolja a terhelés mérséklését.")}
  if(closure?.averageRpe!=null&&closure.averageRpe>=8){adjustment-=10;reasons.push(`A legutóbbi értékelhető hét átlagos RPE-je ${closure.averageRpe.toLocaleString("hu-HU",{maximumFractionDigits:1})}/10 volt, ezért most nem emelünk terhelést.`)}
  if(closure?.plannedMinutes&&closure.actualMinutes>closure.plannedMinutes*1.2){adjustment-=10;reasons.push("A legutóbbi hét edzésideje több mint 20%-kal meghaladta a tervet, ezért a következő hét volumene óvatosabb.")}
  if(missed>=2){adjustment-=10;reasons.push(`${missed} edzés elmaradt; ezeket nem pótoljuk be sűrítéssel.`)}else if(adherence!==null&&adherence>=80&&readiness!==null&&readiness>=75){adjustment+=5;reasons.push(`A ${adherence}%-os tervkövetés és a jó terhelhetőség kis, fokozatos emelést tesz lehetővé.`)}
  if(!closure?.weekPlans.length){adjustment=Math.min(adjustment,0);reasons.push("A legutóbbi értékelhető héthez nem volt előzetes terv, ezért a javaslat nem emeli automatikusan a terhelést.")}else if(closure.feedbackCoverage===null||closure.feedbackCoverage<50){adjustment=Math.min(adjustment,0);reasons.push("A saját edzésérzet kevesebb mint az edzések felénél ismert, ezért a javaslat bizonyossága korlátozott és nem emel automatikusan.")}
  adjustment=Math.max(-35,Math.min(5,adjustment));if(!reasons.length)reasons.push("A rendelkezésre álló jelek alapján a következő hét változtatás nélkül folytatható.");
  const factor=(100+adjustment)/100,adapted=base.map(item=>({...item,id:item.id||`adaptive-${item.date}`,duration:Math.max(20,Math.round(Number(item.duration||45)*factor/5)*5),intensity:adjustment<=-20?"könnyű":adjustment<0&&["magas","közepes–magas"].includes(item.intensity)?"közepes":item.intensity,rpe:adjustment<=-20?Math.min(5,Number(item.rpe||5)):adjustment<0?Math.min(6,Number(item.rpe||6)):item.rpe,note:`${item.note||""}${item.note?" · ":""}Heti lezárás alapján: ${adjustment>0?"+":""}${adjustment}%`,status:"planned"}));
  return {adapted,base,adjustment,reasons,adherence,missed,readiness,closure,checkinDate:checkinEntries[0]?.[0]||null,start:isoDate(nextMonday),end:isoDate(nextEnd)}}
export const emptyPlan=date=>({id:"",date,type:"Kardió",title:"Zone 2 alapozás",duration:60,intensity:"közepes",rpe:5,purpose:"",note:"",status:"planned"});
export const activityMatchesType=(plan,activity)=>plan.type==="Kardió"?["Futás","Túrázás","Kerékpár","Kardió"].includes(activity.type):plan.type===activity.type;
export function evaluatePlan(plan,activities,today){const manual=plan.matchedActivityId&&activities.find(item=>String(item.id)===String(plan.matchedActivityId)),automatic=activities.find(item=>item.date===plan.date&&activityMatchesType(plan,item)),activity=manual||automatic,method=manual?"kézi":automatic?"automatikus":null;if(!activity)return {activity:null,method,status:plan.date<today?"elmaradt":"tervezett",difference:null};const difference=Math.round(Number(activity.durationMin||0)-Number(plan.duration||0)),ratio=Number(activity.durationMin||0)/Math.max(1,Number(plan.duration||0));return {activity,method,status:ratio<.8?"részben teljesült":ratio<=1.2?"teljesült":"túlteljesült",difference}}
